### ISSUE TITLE
Error: Match error: Missing key 'file_type'

### ISSUE THREAD

**Issue by msj121** [Lepozepo/S3#141]
>  Exception while invoking method '_s3_sign' { stack: 'Error: Match error: Missing key \'file_type\'\n    at exports.check (packages/check.js:57:15)\n    at [object Object].Meteor.methods._s3_sign (packages/lepozepo_s3/server/sign_request.coffee:19:3)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira.js:2731:30)\n    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)\n    at packages/ddp-server/livedata_server.js:711:19\n    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)\n    at packages/ddp-server/livedata_server.js:709:40\n    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)\n    at packages/ddp-server/livedata_server.js:707:46\n    at Session.method (packages/ddp-server/livedata_server.js:681:23)',
> I20170213-11:40:12.016(-5)?   source: 'method' }
> I20170213-11:40:12.017(-5)? Sanitized and reported to the client as: Match failed [400]
> I20170213-11:40:12.017(-5)? 

I didn't need to set a "file_tye" when uploading? Is there something I am missing?

I am using code similar to https://github.com/Lepozepo/S3/issues/133 I only noticed this error recently I have tried to run that code before and it worked. Previously my s3 was working fine one file at a time.

Removed personal info:
```
S3.config = {
  key: '..',
  secret: '...',
  bucket: '...'
};
```

**Comment by msj121** [comment]
The problem from #133 seems to be for only single upload
