### ISSUE TITLE
ReferenceError: _ is notdefined

### ISSUE THREAD

**Issue by meet-rizwan** [Lepozepo/S3#164]
i installed this package by running

 `meteor add lepozepo:s3`

i started my server running meteor 

i got this error 

```
W20181211-14:28:31.424(5.5)? (STDERR) /home/rizwan/.meteor/packages/promise/.0.11.1.ihl06c.0g81b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
W20181211-14:28:31.424(5.5)? (STDERR)       throw error;
W20181211-14:28:31.424(5.5)? (STDERR)       ^
W20181211-14:28:31.425(5.5)? (STDERR)
W20181211-14:28:31.425(5.5)? (STDERR) ReferenceError: _ is notdefined
W20181211-14:28:31.425(5.5)? (STDERR)     at packages/lepozepo_s3/server/startup.coffee:17:2
W20181211-14:28:31.425(5.5)? (STDERR)     at Function.time (/home/rizwan/Desktop/rizwan/web/direction-classes/.meteor/local/build/programs/server/profile.js:309:28)
W20181211-14:28:31.425(5.5)? (STDERR)     at /home/rizwan/Desktop/rizwan/web/direction-classes/.meteor/local/build/programs/server/boot.js:427:13
W20181211-14:28:31.425(5.5)? (STDERR)     at /home/rizwan/Desktop/rizwan/web/direction-classes/.meteor/local/build/programs/server/boot.js:472:5
W20181211-14:28:31.425(5.5)? (STDERR)     at Function.run (/home/rizwan/Desktop/rizwan/web/direction-classes/.meteor/local/build/programs/server/profile.js:510:12)
W20181211-14:28:31.426(5.5)? (STDERR)     at /home/rizwan/Desktop/rizwan/web/direction-classes/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by Ethaan** [comment]
`meteor add underscore` the package use it here https://github.com/Lepozepo/S3/blob/master/server/startup.coffee#L17
