### ISSUE TITLE
S3.knox.putStream

### ISSUE THREAD

**Issue by eskimomatt** [Lepozepo/S3#55]
I had this working locally with ease (thank you) - and after testing on server (modulus) all seemed fine -until today! i try and upload a small jpeg, i get a 500 error in my browser console:

**GET http://[my-app].onmodulus.net/sockjs/info?cb=8ufu8t_rw3**

and then the server crashes and restarts, with this in the log:

**/mnt/data/1/programs/server/packages/lepozepo_s3.js:58
        throw new Meteor.Error("S3.knox.putStream", err);
              ^
Error: Error: CERT_UNTRUSTED [S3.knox.putStream]
    at ClientRequest.<anonymous> (packages/lepozepo:s3/server/methods.coffee:55:14)
    at ClientRequest.f (/mnt/data/1/node_modules/once/once.js:17:25)
    at ClientRequest.emit (events.js:117:20)
    at CleartextStream.socketErrorListener (http.js:1552:9)
    at CleartextStream.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1400:19)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)**

**Comment by Lepozepo** [comment]
All right, I've done away with the stream. The package should be much more stable now for you regardless of how you deploy. Let me know if you have any issues ^_^.
