### ISSUE TITLE
Unable to delete file object from S3

### ISSUE THREAD

**Issue by dharshanah** [Lepozepo/S3#70]
Hi,

I am trying to delete a file object from S3. I had uploaded the same using this module. But when i try to 
delete I get an error.

Code :

```var path = "/abc/def.jpg" ;
   S3.delete(path,function(error,response){
   if(error){console.log(error)};
   else { console.log(response)}
});```

Error:
Exception while invoking method '_s3_delete' TypeError: Object #<Object> has no method 'deleteFile'
   at [object Object].Meteor.methods._s3_delete (packages/lepozepo:s3/server/delete_object.coffee:10:11)
   at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
   at packages/ddp/livedata_server.js:648:1
   at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
   at packages/ddp/livedata_server.js:647:1
   at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
   at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
   at packages/ddp/livedata_server.js:546:1

The file is present in the above location. Please clarify.

Thanks in Advance.

**Comment by Lepozepo** [comment]
There might be something strange on your S3.config that's making knox fail. I'll review the code when I get a chance. It would be useful if you did a console.log(S3.knox) just to see if the object exists. If it does not then I need to put an error handler there. Are uploads working?

**Comment by dharshanah** [comment]
Hi,

Thanks for the quick response. I did a console.log(S3.knox) . It is undefined throughout the code flow. But I am able to upload files to S3 without any issues.

My S3 config is present in server.js inside a Meteor.startup block .

S3.config = {
    key: mys3key,
    secret: mys3secret,
    bucket: mys3bucket,
    region: mys3region
};

Thanks

**Comment by s7dhansh** [comment]
@Lepozepo Same error here. Any ideas? S3.knox is defined but S3.knox.deleteFile is not.

**Comment by Lepozepo** [comment]
Maybe the new import/export stuff is messing things up. Try `S3 = require("lepozepo:s3")` I think that should work.

**Comment by nksabertooth** [comment]
Remove the below code from meteor.startup block:
S3.config = {
key: mys3key,
secret: mys3secret,
bucket: mys3bucket,
region: mys3region
};

**Comment by nksabertooth** [comment]
it worked for me :)

**Comment by zcrowe** [comment]
I'm having this issue too - my s3 config is outside the startup block, anyone had any luck with it?
